#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/unbound

PID="$(cat /var/run/unbound.pid 2> /dev/null)"

case "$1" in
  start)
    stat_busy "Starting Unbound DNS resolver"
    [ -z "${PID}" ] && /usr/sbin/unbound $UNBOUND_ARGS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon unbound
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Unbound DNS resolver"
    [ ! -z "${PID}" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon unbound
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

# vim: set ft=sh sw=2 ts=2 et:
